# Generated by Django 5.1.3 on 2025-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatright', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='genimage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='userimage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
