# Generated by Django 5.1.3 on 2025-04-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatright', '0002_alter_userchat_genimage_alter_userchat_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
